name: bus_routes_whitelabel
version: 1.0.0
description: A whitelabel version of the main package.
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  bus_routes_app:
    path: ../Bus_Routes_Modified





environment:
  sdk: '>=3.0.3 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bus.png